language: node_js
node_js: stable
branches:
  only:
  - hexo
cache:
  directories:
  - node_modules
install:
- npm install
script:
- hexo clean
- hexo g
after_script:
- scp -o stricthostkeychecking=no -r public/* aitical@101.132.117.145:/home/aitical/my-blog/public/
- chmod +x ./deploy.sh
- "./deploy.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_69623dba2a4b_key -iv $encrypted_69623dba2a4b_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 101.132.117.145\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
